# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:zsy20050318@tcp(127.0.0.1:3306)/pet_medical_system"
        group: "default"
        descriptionTag: true
        stdTime: true
        overwriteDao: true
        clear: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
