// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// aiAnalysisRecordDao is the data access object for the table ai_analysis_record.
// You can define custom methods on it to extend its functionality as needed.
type aiAnalysisRecordDao struct {
	*internal.AiAnalysisRecordDao
}

var (
	// AiAnalysisRecord is a globally accessible object for table ai_analysis_record operations.
	AiAnalysisRecord = aiAnalysisRecordDao{internal.NewAiAnalysisRecordDao()}
)

// Add your custom methods and functionality below.
