// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// aiMessageDao is the data access object for the table ai_message.
// You can define custom methods on it to extend its functionality as needed.
type aiMessageDao struct {
	*internal.AiMessageDao
}

var (
	// AiMessage is a globally accessible object for table ai_message operations.
	AiMessage = aiMessageDao{internal.NewAiMessageDao()}
)

// Add your custom methods and functionality below.
