// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// aiSessionDao is the data access object for the table ai_session.
// You can define custom methods on it to extend its functionality as needed.
type aiSessionDao struct {
	*internal.AiSessionDao
}

var (
	// AiSession is a globally accessible object for table ai_session operations.
	AiSession = aiSessionDao{internal.NewAiSessionDao()}
)

// Add your custom methods and functionality below.
