// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// doctorDao is the data access object for the table doctor.
// You can define custom methods on it to extend its functionality as needed.
type doctorDao struct {
	*internal.DoctorDao
}

var (
	// Doctor is a globally accessible object for table doctor operations.
	Doctor = doctorDao{internal.NewDoctorDao()}
)

// Add your custom methods and functionality below.
