// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// hospitalDao is the data access object for the table hospital.
// You can define custom methods on it to extend its functionality as needed.
type hospitalDao struct {
	*internal.HospitalDao
}

var (
	// Hospital is a globally accessible object for table hospital operations.
	Hospital = hospitalDao{internal.NewHospitalDao()}
)

// Add your custom methods and functionality below.
