// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// medicalReportDao is the data access object for the table medical_report.
// You can define custom methods on it to extend its functionality as needed.
type medicalReportDao struct {
	*internal.MedicalReportDao
}

var (
	// MedicalReport is a globally accessible object for table medical_report operations.
	MedicalReport = medicalReportDao{internal.NewMedicalReportDao()}
)

// Add your custom methods and functionality below.
