// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// medicalRecordDao is the data access object for the table medical_record.
// You can define custom methods on it to extend its functionality as needed.
type medicalRecordDao struct {
	*internal.MedicalRecordDao
}

var (
	// MedicalRecord is a globally accessible object for table medical_record operations.
	MedicalRecord = medicalRecordDao{internal.NewMedicalRecordDao()}
)

// Add your custom methods and functionality below.
