// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// petDao is the data access object for the table pet.
// You can define custom methods on it to extend its functionality as needed.
type petDao struct {
	*internal.PetDao
}

var (
	// Pet is a globally accessible object for table pet operations.
	Pet = petDao{internal.NewPetDao()}
)

// Add your custom methods and functionality below.
