// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// petVaccinationRecordDao is the data access object for the table pet_vaccination_record.
// You can define custom methods on it to extend its functionality as needed.
type petVaccinationRecordDao struct {
	*internal.PetVaccinationRecordDao
}

var (
	// PetVaccinationRecord is a globally accessible object for table pet_vaccination_record operations.
	PetVaccinationRecord = petVaccinationRecordDao{internal.NewPetVaccinationRecordDao()}
)

// Add your custom methods and functionality below.
