// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// petAllergyRecordDao is the data access object for the table pet_allergy_record.
// You can define custom methods on it to extend its functionality as needed.
type petAllergyRecordDao struct {
	*internal.PetAllergyRecordDao
}

var (
	// PetAllergyRecord is a globally accessible object for table pet_allergy_record operations.
	PetAllergyRecord = petAllergyRecordDao{internal.NewPetAllergyRecordDao()}
)

// Add your custom methods and functionality below.
