// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"PetCare/internal/dao/internal"
)

// petMedicalHistoryDao is the data access object for the table pet_medical_history.
// You can define custom methods on it to extend its functionality as needed.
type petMedicalHistoryDao struct {
	*internal.PetMedicalHistoryDao
}

var (
	// PetMedicalHistory is a globally accessible object for table pet_medical_history operations.
	PetMedicalHistory = petMedicalHistoryDao{internal.NewPetMedicalHistoryDao()}
)

// Add your custom methods and functionality below.
